name = "ghost_vault_backend"
version = "1.0.0"
target = "javascript"

[javascript]
runtime = "node"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
smol = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
